### ISSUE TITLE
whitelist

### ISSUE THREAD

**Issue by tj** [koajs/ratelimit#1]
support

**Comment by tylucaskelley** [comment]
has any progress been made on this?

**Comment by mattbailey** [comment]
I'd love to see this as something built in, but since `ctx` is passed to the id function, you could conditionally send back a random id (e.g. from `uuid`) for certain routes or IPs.  I'm about to have to implement this myself.

**Comment by tuananh** [comment]
i open a pr here to add `whitelist` opts

https://github.com/koajs/ratelimit/pull/44
