### ISSUE TITLE
Custom header names

### ISSUE THREAD

**Issue by ruiquelhas** [koajs/ratelimit#19]
Hi. As far as I can tell, there is currently no support for setting custom header names (for `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset`). Would you consider accepting a PR for it? 

Thanks.

**Comment by coderhaoxin** [comment]
Actually, you can catch `rate-limit errors`, and do anything you want.

**Comment by ruiquelhas** [comment]
Yes, but it feels a bit hacky, don't you think? I would like to override the headers for any kind of response (be it an error or not), and calling `throw()` with a `200 OK` seems weird.

**Comment by coderhaoxin** [comment]
Should we add a hook function such as `onReachLimit(ctx, limit)` ?

cc @tj @jonathanong @koajs/ratelimit

**Comment by dead-horse** [comment]
`onReachLimit` can't resolve @ruiquelhas 's problem, these headers will always set.

**Comment by coderhaoxin** [comment]
```js
if (type onReachLimit === 'function') {
  onReachLimit(this, limit)
} else {
  // set header
  // set body msg
}
```

**Comment by dead-horse** [comment]
https://github.com/koajs/ratelimit/blob/master/index.js#L55

**Comment by ruiquelhas** [comment]
I don't think a hook would be the best solution for my problem. Providing the header names in the `options` and just use them instead will probably make more sense. 

I have branch with those changes, I just wanted to know if it made sense to you before submiting the PR.

**Comment by coderhaoxin** [comment]
> I have a branch with those changes, I just wanted to know if it made sense to you before submiting the PR.

@ruiquelhas can you submit PR first :)

**Comment by coderhaoxin** [comment]
@dead-horse Oh, yea! My fault.
