### ISSUE TITLE
in-memory rate limiting

### ISSUE THREAD

**Issue by KevinGrandon** [koajs/ratelimit#35]
Is in-memory only rate limiting supported? If so, it would be great to update the readme. if not, we'd love to see it added. (Running a toy webiste on a single server and don't want the overhead of setting up redis right now).

Express-rate-limit has this[1], and it would be great if some koa middleware has this as well.

https://github.com/nfriedly/express-rate-limit/blob/master/lib/memory-store.js

**Comment by starzou** [comment]
vote for this issue

**Comment by animir** [comment]
@KevinGrandon Hi, https://github.com/animir/node-rate-limiter-flexible allows that and much-much more

**Comment by tuananh** [comment]
@haoxins would you accept a PR to add multiple drivers to ratelimit? default to using `node-ratelimiter` ?

**Comment by haoxins** [comment]
I'm open to this. :)

**Comment by tuananh** [comment]
@haoxins can you please help reviewing it #45

**Comment by towertop** [comment]
the PR #45 haven't been merged and released? Is it still going to be accepted?
