### ISSUE TITLE
where is the db instance used?

### ISSUE THREAD

**Issue by pke** [koajs/ratelimit#42]
It can be handed into the middleware as an option but it is never used?

**Comment by OutdatedVersion** [comment]
The database instance is, sort of sneakily, used [here](https://github.com/koajs/ratelimit/blob/9be4f5c7e7fd257ef3c87b4621363223f2af71c2/index.js#L46).

By assigning `opts` onto an empty object, `db` goes with it.

**Comment by pke** [comment]
Ah of course ;) Thanks should have looked more closely.
