### ISSUE TITLE
Some enhancements - koa-better-ratelimit

### ISSUE THREAD

**Issue by tunnckoCore** [koajs/ratelimit#5]
Hi folks.

What think for this memory-only-for-now store implementation - [koa-better-ratelimit](https://github.com/tunnckoCore/koa-better-ratelimit) with  **only 4 dependencies**?
I know it's near between `koa-limit` and `koa-ratelimit`, but I think it's smaller and rationally better than `koa-limit` that [is totally broken](https://github.com/koajs/koa-limit/issues/3#issuecomment-42731409) for me.

There's no `db` option, cuz I don't need other than in-memory.
#### Between [koa-better-ratelimit](https://github.com/tunnckoCore/koa-better-ratelimit) and [koa-ratelimit](https://github.com/koajs/ratelimit)
- Support blackList and whiteList options
- Pure in-memory store, no other adapters
- `duration` option in seconds, not in milliseconds
- 7 working tests with Mocha, Supertest and Should
- removed `db` option
- added `Retry-After` header
- added separate 403 and 429 option messages
#### Between [koa-better-ratelimit](https://github.com/tunnckoCore/koa-better-ratelimit) and [koa-limit](https://github.com/koajs/koa-limit)
- koa-limit [is totally broken](https://github.com/koajs/koa-limit/issues/3#issuecomment-42731409) (to v1.0.1)
- removed `redis` and test dependencies
- smaller, better, working, simple
- added separate 403 and 429 option messages

If you want you can add to wiki page :)

**Comment by Globik** [comment]
Hi @tunnckoCore , how to use your middleware in practice? Yes, I see an example provided by you. But not understanble enough how to handle all those custom errors. Shoud it be hanled in a router system?

**Comment by tunnckoCore** [comment]
haha, pretty old issue bumped.

@Globik, i'm working on v3. Actually it is almost ready and it is in the master branch. But was busy last month or so. It is pretty working and it is for Koa2.

Please open issue there and explain, give some examples and etc.

**Comment by Globik** [comment]
Ok, @tunnckoCore  I'll look at v3.
