### ISSUE TITLE
async-ratelimiter does not support `redis` library

### ISSUE THREAD

**Issue by scragg0x** [koajs/ratelimit#60]
The old `ratelimiter` library has an `ioredis` check:

```js
var isIoRedis = Array.isArray(res[0]);
var count = parseInt(isIoRedis ? res[1][1] : res[1]);
var oldest = parseInt(isIoRedis ? res[3][1] : res[3]);
var oldestInRange = parseInt(isIoRedis ? res[4][1] : res[4]);
```

but `async-ratelimiter` does not. 

This will cause erroneous 429s to occur with the latest version of `koa-ratelimit` for people using the regular redis library. Please list this as a breaking change.

https://github.com/microlinkhq/async-ratelimiter/issues/22

> I'm not interested into support node-redis since ioredis have all the features necessaries and the project is well maintained 🙂

**Comment by tony3918** [comment]
Not sure if this is the same issue but when I pass `RedisClient` from [node-redis](https://github.com/NodeRedis/node-redis) into koa-ratelimit's `db`, an error occurs `Cannot read property '1' of undefined`

**Comment by miladmeidanshahi** [comment]
same issue doesn't work with `node-redis`.

**Comment by 3imed-jaberi** [comment]
I open a PR in `async-ratelimiter` [here](https://github.com/microlinkhq/async-ratelimiter/pull/28). Some time and everything will be fine.

**Comment by 3imed-jaberi** [comment]
Hi guys, I fixed the missing behave in async-ratelimiter and now everything work just I wait @niftylettuce to merge my PR #62 and everything done 🎉.

**Comment by niftylettuce** [comment]
v5.0.1 released to npm

https://github.com/koajs/ratelimit/releases/tag/v5.0.1
